# Generated by Django 4.2.13 on 2026-06-05 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TentativeConnexion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse_ip', models.GenericIPAddressField(verbose_name='Adresse IP')),
                ('username', models.CharField(blank=True, max_length=150)),
                ('nb_tentatives', models.PositiveIntegerField(default=1)),
                ('premiere_tentative', models.DateTimeField(auto_now_add=True)),
                ('derniere_tentative', models.DateTimeField(auto_now=True)),
                ('est_bloque', models.BooleanField(default=False)),
                ('fin_blocage', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tentative de connexion',
                'verbose_name_plural': 'Tentatives de connexion',
                'ordering': ['-derniere_tentative'],
            },
        ),
        migrations.CreateModel(
            name='LogActivite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_action', models.CharField(choices=[('connexion', 'Connexion'), ('deconnexion', 'Déconnexion'), ('telechargement', 'Téléchargement'), ('upload', 'Upload épreuve'), ('quiz', 'Passage quiz'), ('ia', 'Requête IA'), ('admin', 'Action admin'), ('alerte', 'Alerte sécurité')], max_length=30)),
                ('description', models.TextField()),
                ('adresse_ip', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('est_suspect', models.BooleanField(default=False)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Log d'activité",
                'verbose_name_plural': "Logs d'activité",
                'ordering': ['-date_action'],
            },
        ),
        migrations.CreateModel(
            name='AlerteSecurite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.CharField(choices=[('info', 'Information'), ('avertissement', 'Avertissement'), ('critique', 'Critique')], default='avertissement', max_length=20)),
                ('titre', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('date_alerte', models.DateTimeField(auto_now_add=True)),
                ('est_resolue', models.BooleanField(default=False)),
                ('resolue_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alerte de sécurité',
                'verbose_name_plural': 'Alertes de sécurité',
                'ordering': ['-date_alerte'],
            },
        ),
    ]
