# Generated by Django 4.2.13 on 2026-06-05 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Epreuve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name="Titre de l'épreuve")),
                ('type_examen', models.CharField(choices=[('baccalaureat', 'Baccalauréat'), ('bepc', 'BEPC'), ('probatoire', 'Probatoire'), ('concours', 'Concours'), ('ds', 'Devoir Surveillé'), ('examen_final', 'Examen Final'), ('entrainement', 'Entraînement')], max_length=30, verbose_name="Type d'examen")),
                ('annee', models.PositiveIntegerField(verbose_name='Année')),
                ('fichier', models.FileField(upload_to='epreuves/%Y/', verbose_name='Fichier (PDF/DOC)')),
                ('corrige', models.FileField(blank=True, null=True, upload_to='epreuves/corriges/%Y/', verbose_name='Corrigé (optionnel)')),
                ('description', models.TextField(blank=True)),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('nb_telechargements', models.PositiveIntegerField(default=0, verbose_name='Téléchargements')),
                ('est_valide', models.BooleanField(default=True, verbose_name='Validé')),
            ],
            options={
                'verbose_name': 'Épreuve',
                'verbose_name_plural': 'Épreuves',
                'ordering': ['-annee', '-date_upload'],
            },
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Matière')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icone', models.CharField(default='book', max_length=50, verbose_name='Icône Bootstrap')),
            ],
            options={
                'verbose_name': 'Matière',
                'verbose_name_plural': 'Matières',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, verbose_name='Niveau')),
                ('cycle', models.CharField(choices=[('primaire', 'Primaire'), ('college', 'Collège'), ('lycee', 'Lycée'), ('superieur', 'Supérieur')], max_length=20)),
                ('ordre', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Niveau',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Telechargement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse_ip', models.GenericIPAddressField()),
                ('date_telechargement', models.DateTimeField(auto_now_add=True)),
                ('epreuve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telechargements', to='epreuves.epreuve')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Téléchargement',
                'ordering': ['-date_telechargement'],
            },
        ),
        migrations.AddField(
            model_name='epreuve',
            name='matiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epreuves', to='epreuves.matiere'),
        ),
        migrations.AddField(
            model_name='epreuve',
            name='niveau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epreuves', to='epreuves.niveau'),
        ),
        migrations.AddField(
            model_name='epreuve',
            name='uploade_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='epreuves_uploadees', to=settings.AUTH_USER_MODEL),
        ),
    ]
