# Generated by Django 4.2.13 on 2026-06-05 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('epreuves', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Choix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.CharField(max_length=500)),
                ('est_correct', models.BooleanField(default=False)),
                ('ordre', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enonce', models.TextField(verbose_name='Énoncé')),
                ('type_question', models.CharField(choices=[('qcm', 'Choix Multiple (QCM)'), ('vrai_faux', 'Vrai / Faux'), ('texte', 'Réponse Texte')], default='qcm', max_length=20)),
                ('points', models.PositiveIntegerField(default=1)),
                ('explication', models.TextField(blank=True, verbose_name='Explication de la réponse')),
                ('ordre', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('duree_minutes', models.PositiveIntegerField(default=30, verbose_name='Durée (minutes)')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('est_actif', models.BooleanField(default=True)),
                ('nb_tentatives_max', models.PositiveIntegerField(default=3)),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epreuves.matiere')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epreuves.niveau')),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quiz',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='SessionQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('score_obtenu', models.FloatField(default=0)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('termine', 'Terminé'), ('abandonne', 'Abandonné')], default='en_cours', max_length=20)),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Session Quiz',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='ReponseEleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte_reponse', models.TextField(blank=True)),
                ('est_correcte', models.BooleanField(default=False)),
                ('points_obtenus', models.FloatField(default=0)),
                ('choix_selectionne', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.choix')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='quiz.sessionquiz')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.quiz'),
        ),
        migrations.AddField(
            model_name='choix',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choix', to='quiz.question'),
        ),
    ]
